### ISSUE TITLE
selection checks are too strict for `adjust_predictions_custom()` with regression

### ISSUE THREAD

**Issue by simonpcouch** [tidymodels/tailor#61]
```r
library(tibble)

set.seed(1)
d_calibration <- tibble(y = rnorm(100), y_pred = y/2 + rnorm(100))
d_test <- tibble(y = rnorm(100), y_pred = y/2 + rnorm(100))

tlr <-
  tailor() %>%
  adjust_numeric_calibration() %>%
  adjust_numeric_range(lower_limit = 2) %>%
  adjust_predictions_custom(squared = y_pred^2)

tlr_fit <- fit(tlr, d_calibration, outcome = y, estimate = y_pred)
#> Error in `fit()`:
#> ! `probabilities` must select at least one column.
#> ✖ Selector `c()` did not match any columns in `.data`.
```

**Comment by lattaai10** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the adjust_numeric_calibration function to remove the check for probability columns, which is not relevant for numeric calibration. This should resolve the error when fitting the tailor object.

You can review changes in this commit: https://github.com/lattaai10/tidymodels-tailor-61/commit/de39945776e6d48e08c16437d4f728dff88ff08b.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
